import { useEffect, useMemo, useState, type FormEvent } from "react";
import { Link, useNavigate } from "@tanstack/react-router";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { addMonths, eachDayOfInterval, endOfMonth, endOfWeek, format, isSameMonth, startOfMonth, startOfWeek, subMonths } from "date-fns";
import { ArrowRight, BookOpen, CalendarDays, CheckCircle2, ChevronLeft, ChevronRight, Circle, Heart, Home, LockKeyhole, Menu, MoreHorizontal, NotebookPen, Plus, Search, Settings, Sparkle, Target, Trash2, Users, X } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import type { Database } from "@/integrations/supabase/types";

type Item = Database["public"]["Tables"]["life_items"]["Row"];
type Kind = "diary" | "task" | "goal" | "note" | "memory" | "event";
type View = "home" | Kind | "settings" | "profile";
const kinds: { kind: Kind; label: string; icon: typeof BookOpen }[] = [
  { kind: "diary", label: "Diary", icon: BookOpen }, { kind: "task", label: "Tasks", icon: CheckCircle2 },
  { kind: "goal", label: "Goals", icon: Target }, { kind: "note", label: "Notes", icon: NotebookPen },
  { kind: "memory", label: "Memories", icon: Heart }, { kind: "event", label: "Events", icon: CalendarDays },
];
const labels: Record<Kind, string> = { diary: "Diary", task: "Tasks", goal: "Goals", note: "Notes", memory: "Memories", event: "Events" };
const today = () => format(new Date(), "yyyy-MM-dd");

export function Workspace({ view }: { view: View }) {
  const navigate = useNavigate(); const queryClient = useQueryClient();
  const [userId, setUserId] = useState<string | null>(null);
  const [name, setName] = useState(""); const [username, setUsername] = useState("");
  const [theme, setTheme] = useState("system");
  const [bio, setBio] = useState(""); const [weekStart, setWeekStart] = useState("monday"); const [startPage, setStartPage] = useState("home");
  const [avatarPath, setAvatarPath] = useState<string | null>(null); const [avatarUrl, setAvatarUrl] = useState<string | null>(null); const [uploading, setUploading] = useState(false);
  const [email, setEmail] = useState(""); const [newPassword, setNewPassword] = useState(""); const [confirmPassword, setConfirmPassword] = useState(""); const [pwMessage, setPwMessage] = useState("");
  const [editor, setEditor] = useState<Kind | null>(null); const [editing, setEditing] = useState<Item | null>(null);
  const [title, setTitle] = useState(""); const [body, setBody] = useState(""); const [date, setDate] = useState(today()); const [mood, setMood] = useState<string | null>(null);
  const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [menuOpen, setMenuOpen] = useState(false); const [quickOpen, setQuickOpen] = useState(false);
  const [month, setMonth] = useState(new Date()); const [selectedDate, setSelectedDate] = useState(today());
  const [search, setSearch] = useState("");

  useEffect(() => {
    supabase.auth.getUser().then(async ({ data }) => {
      if (!data.user) return;
      setUserId(data.user.id); setEmail(data.user.email ?? "");
      const { data: profile } = await supabase.from("profiles").select("display_name,username,theme,avatar_url,bio,week_start,start_page").eq("id", data.user.id).maybeSingle();
      if (profile) { setName(profile.display_name); setUsername(profile.username ?? ""); setTheme(profile.theme); setBio(profile.bio); setWeekStart(profile.week_start); setStartPage(profile.start_page); setAvatarPath(profile.avatar_url); }
      else { const displayName = String(data.user.user_metadata?.["display_name"] ?? data.user.user_metadata?.["full_name"] ?? ""); await supabase.from("profiles").upsert({ id: data.user.id, display_name: displayName }); setName(displayName); }
    });
  }, []);
  useEffect(() => {
    if (!avatarPath) { setAvatarUrl(null); return; }
    supabase.storage.from("avatars").createSignedUrl(avatarPath, 60 * 60).then(({ data }) => setAvatarUrl(data?.signedUrl ?? null));
  }, [avatarPath]);
  useEffect(() => { document.documentElement.classList.toggle("dark", theme === "dark" || (theme === "system" && window.matchMedia("(prefers-color-scheme: dark)").matches)); }, [theme]);
  const { data: items = [], isLoading, error: loadError } = useQuery({ queryKey: ["life-items", userId], enabled: !!userId, queryFn: async () => {
    const { data, error } = await supabase.from("life_items").select("*").order("occurred_on", { ascending: false }).order("created_at", { ascending: false });
    if (error) throw error; return data;
  } });
  const invalidate = () => queryClient.invalidateQueries({ queryKey: ["life-items", userId] });
  const todayItems = items.filter(item => item.occurred_on === today());
  const taskCount = items.filter(item => item.kind === "task" && !item.completed).length;
  const visible = useMemo(() => items.filter(item => (view === "home" || view === "profile" || view === "settings" || item.kind === view) && (view !== "diary" || item.occurred_on === selectedDate) && (!search || `${item.title} ${item.body}`.toLowerCase().includes(search.toLowerCase()))), [items, view, selectedDate, search]);
  const calendarDays = eachDayOfInterval({ start: startOfWeek(startOfMonth(month)), end: endOfWeek(endOfMonth(month)) });
  const greeting = new Date().getHours() < 12 ? "Good morning" : new Date().getHours() < 17 ? "Good afternoon" : "Good evening";
  function openEditor(kind: Kind, item?: Item) { setQuickOpen(false); setEditor(kind); setEditing(item ?? null); setTitle(item?.title ?? ""); setBody(item?.body ?? ""); setDate(item?.occurred_on ?? (kind === "diary" ? selectedDate : today())); setMood(item?.mood ?? null); setMessage(""); }
  async function saveItem(e: FormEvent) {
    e.preventDefault(); if (!userId || !editor) return;
    setSaving(true); setMessage("");
    const payload = { title: title.trim(), body: body.trim(), occurred_on: date, mood: editor === "diary" ? mood : null };
    const result = editing ? await supabase.from("life_items").update(payload).eq("id", editing.id) : await supabase.from("life_items").insert({ ...payload, kind: editor, owner_id: userId });
    setSaving(false); if (result.error) { setMessage(result.error.message); return; } setEditor(null); await invalidate();
  }
  async function toggleTask(item: Item) { const { error } = await supabase.from("life_items").update({ completed: !item.completed }).eq("id", item.id); if (error) setMessage(error.message); else await invalidate(); }
  async function deleteItem(item: Item) { if (!window.confirm(`Delete this ${item.kind}? This cannot be undone.`)) return; const { error } = await supabase.from("life_items").delete().eq("id", item.id); if (error) setMessage(error.message); else await invalidate(); }
  async function saveProfile(e: FormEvent) { e.preventDefault(); if (!userId) return; if (!name.trim()) { setMessage("Please add a display name."); return; } const { error } = await supabase.from("profiles").update({ display_name: name.trim(), username: username.trim() || null, bio: bio.trim() }).eq("id", userId); setMessage(error ? (error.code === "23505" ? "That username is taken." : error.message) : "Profile saved."); }
  async function uploadAvatar(file: File | undefined) {
    if (!file || !userId) return;
    if (!file.type.startsWith("image/")) { setMessage("Please choose an image file."); return; }
    if (file.size > 5 * 1024 * 1024) { setMessage("Pictures must be under 5 MB."); return; }
    setUploading(true); setMessage("");
    const path = `${userId}/avatar-${Date.now()}.${file.name.split(".").pop() || "jpg"}`;
    const { error } = await supabase.storage.from("avatars").upload(path, file, { contentType: file.type });
    if (error) { setUploading(false); setMessage(error.message); return; }
    const old = avatarPath;
    const { error: updateError } = await supabase.from("profiles").update({ avatar_url: path }).eq("id", userId);
    setUploading(false);
    if (updateError) { setMessage(updateError.message); return; }
    if (old) await supabase.storage.from("avatars").remove([old]);
    setAvatarPath(path); setMessage("Profile picture updated.");
  }
  async function removeAvatar() {
    if (!userId || !avatarPath) return;
    const { error } = await supabase.from("profiles").update({ avatar_url: null }).eq("id", userId);
    if (error) { setMessage(error.message); return; }
    await supabase.storage.from("avatars").remove([avatarPath]); setAvatarPath(null); setMessage("Profile picture removed.");
  }
  async function changePassword(e: FormEvent) {
    e.preventDefault(); setPwMessage("");
    if (newPassword.length < 8) { setPwMessage("Use at least 8 characters."); return; }
    if (newPassword !== confirmPassword) { setPwMessage("Passwords don't match."); return; }
    const { error } = await supabase.auth.updateUser({ password: newPassword });
    if (error) { setPwMessage(error.message); return; }
    setNewPassword(""); setConfirmPassword(""); setPwMessage("Password updated.");
  }
  async function savePref(patch: { theme?: string; week_start?: string; start_page?: string }) {
    if (!userId) return; const { error } = await supabase.from("profiles").update(patch).eq("id", userId); setMessage(error ? error.message : "Preferences saved.");
  }
  const Avatar = ({ size }: { size: string }) => avatarUrl ? <img src={avatarUrl} alt="Profile picture" className={`${size} rounded-full object-cover`} /> : <span className={`${size} flex items-center justify-center rounded-full bg-leaf font-display text-leaf-foreground`}>{name?.charAt(0).toUpperCase() || "D"}</span>;
  async function signOut() { await queryClient.cancelQueries(); queryClient.clear(); await supabase.auth.signOut(); navigate({ to: "/auth", replace: true }); }
  const NavLink = ({ to, icon: Icon, text, active }: { to: string; icon: typeof Home; text: string; active: boolean }) => <Link to={to} className={`flex items-center gap-3 rounded-md px-3 py-2.5 text-sm transition-colors ${active ? "bg-accent font-semibold text-primary" : "text-muted-foreground hover:bg-muted hover:text-foreground"}`}><Icon className="size-[18px]" strokeWidth={1.8} /><span>{text}</span>{text === "Tasks" && taskCount > 0 && <span className="ml-auto text-xs text-muted-foreground">{taskCount}</span>}</Link>;
  const SectionLabel = ({ children }: { children: string }) => <div className="px-3 pb-2 pt-6 text-[10px] font-bold uppercase text-muted-foreground">{children}</div>;

  return <div className="min-h-screen bg-background text-foreground lg:flex">
    <aside className={`fixed inset-y-0 left-0 z-40 w-64 border-r border-border bg-card px-4 py-6 transition-transform lg:sticky lg:top-0 lg:h-screen lg:translate-x-0 ${menuOpen ? "translate-x-0" : "-translate-x-full"}`}>
      <div className="mb-8 flex items-center justify-between px-2"><Link to="/home" className="flex items-center gap-2 font-display text-[25px] font-semibold text-primary"><span className="flex size-9 items-center justify-center rounded-md bg-wash font-display text-2xl">D</span> dayraa<span className="text-coral">.</span></Link><Button size="icon" variant="ghost" className="lg:hidden" onClick={() => setMenuOpen(false)} aria-label="Close menu"><X /></Button></div>
      <div className="scrollbar-none max-h-[calc(100vh-190px)] overflow-y-auto"><SectionLabel>YOUR SPACE</SectionLabel><nav className="space-y-0.5" onClick={() => setMenuOpen(false)}><NavLink to="/home" icon={Home} text="Home" active={view === "home"} />{kinds.map(({ kind, label, icon }) => <NavLink key={kind} to={`/${kind}`} icon={icon} text={label} active={view === kind} />)}</nav><SectionLabel>YOU</SectionLabel><nav className="space-y-0.5" onClick={() => setMenuOpen(false)}><NavLink to="/profile" icon={Users} text="Profile" active={view === "profile"} /><NavLink to="/settings" icon={Settings} text="Settings" active={view === "settings"} /></nav></div>
      <div className="absolute bottom-6 left-4 right-4 border-t pt-5"><Link to="/profile" className="flex items-center gap-3 rounded-md px-2 py-2 hover:bg-muted"><span className="flex size-9 items-center justify-center rounded-full bg-leaf font-display text-lg text-leaf-foreground">{name?.charAt(0).toUpperCase() || "D"}</span><span className="min-w-0"><span className="block truncate text-sm font-semibold">{name || "Your space"}</span><span className="block text-xs text-muted-foreground">Private space</span></span><MoreHorizontal className="ml-auto size-4 text-muted-foreground" /></Link></div>
    </aside>
    {menuOpen && <div className="fixed inset-0 z-30 bg-foreground/30 lg:hidden" onClick={() => setMenuOpen(false)} />}
    <div className="min-w-0 flex-1 pb-24 lg:pb-0">
      <header className="sticky top-0 z-20 flex h-16 items-center justify-between border-b border-border bg-background/95 px-5 backdrop-blur-sm sm:px-10 lg:px-12"><div className="flex items-center gap-2"><Button size="icon" variant="ghost" className="lg:hidden" onClick={() => setMenuOpen(true)} aria-label="Open menu"><Menu /></Button><span className="text-sm font-semibold">{view === "home" ? "Home" : view === "profile" ? "Profile" : view === "settings" ? "Settings" : labels[view]}</span></div><div className="flex items-center gap-2"><span className="hidden items-center gap-1.5 text-xs text-muted-foreground sm:flex"><LockKeyhole className="size-3.5" /> Just for you</span><div className="mx-2 hidden h-5 w-px bg-border sm:block" /><Button size="sm" onClick={() => setQuickOpen(true)}><Plus className="size-4" /> Add new</Button></div></header>
      <main className="mx-auto max-w-6xl px-5 py-8 sm:px-10 lg:px-12 lg:py-11">
        {message && <div role="status" className="mb-5 rounded-md bg-accent px-4 py-3 text-sm text-primary">{message}<Button variant="ghost" size="icon" className="ml-2 h-6 w-6" onClick={() => setMessage("")} aria-label="Dismiss message"><X /></Button></div>}
        {loadError && <p role="alert" className="mb-6 text-sm text-destructive">Could not load your space. Please refresh and try again.</p>}
        {view === "home" && <>
          <div className="mb-9 flex flex-wrap items-end justify-between gap-5"><div><p className="mb-3 flex items-center gap-2 text-xs font-bold uppercase text-muted-foreground"><span className="h-px w-6 bg-coral" /> {format(new Date(), "EEEE, MMMM d, yyyy")}</p><h1 className="text-4xl sm:text-5xl">{greeting}{name ? `, ${name.split(" ")[0]}` : ""}<span className="text-coral">.</span></h1><p className="mt-3 text-sm text-muted-foreground">A fresh page for whatever today brings.</p></div><span className="rounded-md border border-border bg-card px-3 py-2 text-xs text-muted-foreground"><LockKeyhole className="mr-1 inline size-3.5" /> Everything here is private</span></div>
          <div className="grid gap-5 lg:grid-cols-[minmax(0,1.5fr)_minmax(260px,1fr)]"><div className="min-h-72 overflow-hidden rounded-lg border border-border bg-card"><div className="border-b border-border px-6 py-5"><div className="flex items-center justify-between"><h2 className="text-xl">Today, in a nutshell</h2><span className="text-xs text-muted-foreground">{format(new Date(), "MMM d")}</span></div></div><div className="px-6 py-5">{todayItems.length ? <div className="space-y-4">{todayItems.slice(0,5).map(item => <ItemRow key={item.id} item={item} onEdit={() => openEditor(item.kind as Kind, item)} onToggle={() => toggleTask(item)} onDelete={() => deleteItem(item)} />)}</div> : <div className="flex h-40 flex-col items-center justify-center text-center"><span className="mb-3 flex size-12 items-center justify-center rounded-full bg-wash text-coral"><Sparkle className="size-5" /></span><p className="font-display text-lg">A blank page is a beautiful start.</p><p className="mt-1 text-xs text-muted-foreground">What's on your mind today?</p><Button variant="link" className="mt-2" onClick={() => openEditor("diary")}>Write a little something <ArrowRight /></Button></div>}</div></div><div className="flex min-h-72 flex-col justify-between rounded-lg bg-leaf p-6 text-leaf-foreground"><div><div className="mb-5 flex size-10 items-center justify-center rounded-full bg-card/60"><Target className="size-5" /></div><h2 className="text-2xl">Small steps count.</h2><p className="mt-2 max-w-xs text-sm leading-6">{taskCount ? `${taskCount} ${taskCount === 1 ? "task" : "tasks"} waiting for you. Take them one at a time.` : "Your plans can grow at your own pace. Start with one little thing."}</p></div><Link to="/task" className="mt-6 inline-flex items-center gap-2 text-sm font-semibold hover:underline">See your tasks <ArrowRight className="size-4" /></Link></div></div>
          <div className="mt-11 flex items-center justify-between"><h2 className="text-2xl">The little things, all together</h2></div><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">{kinds.map(({ kind, label, icon: Icon }) => <Link to={`/${kind}`} key={kind} className="group flex min-h-32 flex-col justify-between rounded-lg border border-border bg-card p-4 transition-colors hover:border-coral"><Icon className="size-5 text-primary" strokeWidth={1.7} /><div><span className="block text-sm font-semibold">{label}</span><span className="mt-1 block text-xs text-muted-foreground">{items.filter(item => item.kind === kind).length} saved</span></div></Link>)}</div>
          <div className="mt-12 grid gap-5 lg:grid-cols-[1fr_1.5fr]"><div className="rounded-lg bg-wash p-6"><Heart className="mb-5 size-5 text-coral" /><h2 className="text-2xl">Keep a moment close.</h2><p className="mt-2 max-w-xs text-sm leading-6 text-muted-foreground">The things you might forget are often the things worth keeping.</p><Button variant="outline" className="mt-6 bg-card" onClick={() => openEditor("memory")}>Save a memory <ArrowRight /></Button></div><div className="rounded-lg border border-border bg-card p-6"><div className="flex items-center justify-between"><h2 className="text-xl">Recently added</h2><span className="text-xs text-muted-foreground">Your space</span></div>{items.length ? <div className="mt-5 space-y-4">{items.slice(0,3).map(item => <ItemRow key={item.id} item={item} onEdit={() => openEditor(item.kind as Kind, item)} onToggle={() => toggleTask(item)} onDelete={() => deleteItem(item)} />)}</div> : <p className="mt-8 text-sm text-muted-foreground">Your entries will find a home here.</p>}</div></div>
        </>}
        {kinds.some(k => k.kind === view) && <><div className="mb-8 flex flex-wrap items-end justify-between gap-5"><div><p className="mb-3 text-xs font-bold uppercase text-coral">YOUR SPACE / {labels[view as Kind].toUpperCase()}</p><h1 className="text-4xl sm:text-5xl">{view === "diary" ? "Your days, your words." : view === "task" ? "A little at a time." : view === "goal" ? "What you're growing toward." : view === "note" ? "Thoughts worth keeping." : view === "memory" ? "Moments to remember." : "What's coming up."}</h1><p className="mt-3 text-sm text-muted-foreground">Only you can see what's here.</p></div><Button onClick={() => openEditor(view as Kind)}><Plus /> Add {view === "diary" || view === "event" ? "an" : "a"} {view === "diary" ? "entry" : view}</Button></div>
        {view === "diary" && <div className="mb-8 grid gap-5 lg:grid-cols-[310px_1fr]"><div className="rounded-lg border border-border bg-card p-5"><div className="mb-5 flex items-center justify-between"><Button size="icon" variant="ghost" onClick={() => setMonth(subMonths(month, 1))} aria-label="Previous month"><ChevronLeft /></Button><span className="text-sm font-semibold">{format(month, "MMMM yyyy")}</span><Button size="icon" variant="ghost" onClick={() => setMonth(addMonths(month, 1))} aria-label="Next month"><ChevronRight /></Button></div><div className="grid grid-cols-7 text-center text-[10px] text-muted-foreground">{["S","M","T","W","T","F","S"].map((day, i) => <span key={i} className="py-2">{day}</span>)}</div><div className="grid grid-cols-7 gap-1">{calendarDays.map(day => { const iso = format(day, "yyyy-MM-dd"); const hasEntry = items.some(item => item.kind === "diary" && item.occurred_on === iso); return <Button key={iso} size="icon" variant={selectedDate === iso ? "default" : "ghost"} className={`relative size-9 text-xs ${!isSameMonth(day, month) ? "opacity-30" : ""}`} onClick={() => setSelectedDate(iso)} aria-label={format(day, "MMMM d, yyyy")}>{format(day, "d")}{hasEntry && <span className={`absolute bottom-1 size-1 rounded-full ${selectedDate === iso ? "bg-primary-foreground" : "bg-coral"}`} />}</Button>; })}</div></div><div className="flex min-h-64 flex-col justify-center rounded-lg bg-wash p-8"><span className="mb-4 text-xs font-semibold uppercase text-coral">{format(new Date(selectedDate + "T12:00:00"), "EEEE, MMMM d")}</span><h2 className="text-3xl">What was today like?</h2><p className="mt-3 max-w-md text-sm leading-6 text-muted-foreground">A few lines, a little feeling, or an entire story. There's no right way to remember a day.</p><Button className="mt-6 w-fit" onClick={() => openEditor("diary")}>Write an entry <ArrowRight /></Button></div></div>}
        <div className="mb-5 flex items-center justify-between gap-4"><h2 className="text-xl">{view === "diary" ? format(new Date(selectedDate + "T12:00:00"), "Entries for MMMM d") : `Your ${labels[view as Kind].toLowerCase()}`}</h2><div className="relative max-w-44"><Search className="absolute left-2.5 top-2.5 size-4 text-muted-foreground" /><Input className="pl-8" value={search} onChange={e => setSearch(e.target.value)} placeholder="Search here" aria-label="Search entries" /></div></div>
        {isLoading ? <p className="py-12 text-sm text-muted-foreground">Opening your space…</p> : visible.length ? <div className="divide-y divide-border rounded-lg border border-border bg-card px-5 sm:px-7">{visible.map(item => <ItemRow key={item.id} item={item} onEdit={() => openEditor(item.kind as Kind, item)} onToggle={() => toggleTask(item)} onDelete={() => deleteItem(item)} />)}</div> : <div className="flex min-h-48 flex-col items-center justify-center rounded-lg border border-dashed border-border text-center"><BookOpen className="mb-3 size-6 text-coral" /><p className="font-display text-xl">{search ? "Nothing matches your search." : "Nothing here yet. That's okay."}</p><p className="mt-1 text-sm text-muted-foreground">{search ? "Try another word." : "Begin whenever you're ready."}</p></div>}</>}
        {view === "profile" && <><p className="mb-3 text-xs font-bold uppercase text-coral">A LITTLE ABOUT YOU</p><h1 className="text-4xl">Your profile.</h1><div className="mt-8 flex items-center gap-5"><span className="flex size-20 items-center justify-center rounded-full bg-leaf font-display text-4xl text-leaf-foreground">{name?.charAt(0).toUpperCase() || "D"}</span><div><h2 className="text-2xl">{name || "Your name"}</h2><p className="text-sm text-muted-foreground">A private home for your life.</p></div></div><form onSubmit={saveProfile} className="mt-9 max-w-md space-y-5"><label className="block text-sm font-medium">Display name<Input className="mt-2 bg-card" value={name} onChange={e => setName(e.target.value)} maxLength={80} /></label><label className="block text-sm font-medium">Username<Input className="mt-2 bg-card" value={username} onChange={e => setUsername(e.target.value)} maxLength={40} placeholder="Optional" /></label><Button type="submit">Save profile</Button></form></>}
        {view === "settings" && <><p className="mb-3 text-xs font-bold uppercase text-coral">MAKE IT YOURS</p><h1 className="text-4xl">Settings.</h1><div className="mt-9 max-w-lg space-y-9"><section><h2 className="text-xl">Appearance</h2><p className="mt-1 text-sm text-muted-foreground">Choose how your space looks.</p><div className="mt-4 flex gap-2">{["system","light","dark"].map(option => <Button key={option} variant={theme === option ? "default" : "outline"} className="capitalize" onClick={async () => { setTheme(option); if (userId) { const { error } = await supabase.from("profiles").update({ theme: option }).eq("id", userId); if (error) setMessage(error.message); } }}>{option}</Button>)}</div></section><section className="border-t border-border pt-7"><h2 className="text-xl">Privacy</h2><p className="mt-2 flex items-center gap-2 text-sm text-muted-foreground"><LockKeyhole className="size-4" /> Your entries are private and visible only to you.</p></section><section className="border-t border-border pt-7"><h2 className="text-xl">Account</h2><Button variant="outline" className="mt-4" onClick={signOut}>Sign out</Button></section></div></>}
      </main>
    </div>
    <nav className="fixed bottom-0 left-0 right-0 z-20 grid h-16 grid-cols-5 border-t border-border bg-card lg:hidden"><Link to="/home" className={`flex flex-col items-center justify-center gap-1 text-[10px] ${view === "home" ? "text-primary" : "text-muted-foreground"}`}><Home className="size-5" />Home</Link><Link to="/diary" className={`flex flex-col items-center justify-center gap-1 text-[10px] ${view === "diary" ? "text-primary" : "text-muted-foreground"}`}><BookOpen className="size-5" />Diary</Link><Button variant="ghost" className="flex h-full flex-col gap-0 text-[10px]" onClick={() => setQuickOpen(true)}><span className="-mt-4 mb-1 flex size-11 items-center justify-center rounded-full bg-primary text-primary-foreground shadow-md"><Plus className="size-6" /></span>Add</Button><Link to="/goal" className={`flex flex-col items-center justify-center gap-1 text-[10px] ${view === "goal" ? "text-primary" : "text-muted-foreground"}`}><Target className="size-5" />Goals</Link><Link to="/profile" className={`flex flex-col items-center justify-center gap-1 text-[10px] ${view === "profile" ? "text-primary" : "text-muted-foreground"}`}><Users className="size-5" />Me</Link></nav>
    <Dialog open={quickOpen} onOpenChange={setQuickOpen}><DialogContent className="max-w-sm rounded-lg"><DialogHeader><DialogTitle className="font-display text-2xl">Add to your space</DialogTitle><DialogDescription>Pick what you'd like to keep.</DialogDescription></DialogHeader><div className="grid grid-cols-2 gap-2 pt-3">{kinds.map(({kind,label,icon:Icon}) => <Button key={kind} variant="outline" className="h-14 justify-start gap-3" onClick={() => openEditor(kind)}><Icon className="size-5 text-primary" />{kind === "diary" ? "Diary entry" : kind === "memory" ? "Memory" : kind === "event" ? "Event" : label.slice(0,-1)}</Button>)}</div></DialogContent></Dialog>
    <Dialog open={editor !== null} onOpenChange={open => { if (!open) setEditor(null); }}><DialogContent className="max-h-[90vh] max-w-lg overflow-y-auto rounded-lg"><DialogHeader><DialogTitle className="font-display text-2xl">{editing ? "Edit" : "New"} {editor === "diary" ? "diary entry" : editor}</DialogTitle><DialogDescription><LockKeyhole className="mr-1 inline size-3" /> Only you can see this.</DialogDescription></DialogHeader><form onSubmit={saveItem} className="space-y-4 pt-2"><label className="block text-sm font-medium">{editor === "diary" ? "Give this day a title" : "Title"}<Input className="mt-2 bg-card" value={title} maxLength={180} onChange={e => setTitle(e.target.value)} placeholder={editor === "diary" ? "A day to remember…" : "What's on your mind?"} required /></label><label className="block text-sm font-medium">{editor === "task" ? "Details (optional)" : "Your words"}<Textarea className="mt-2 min-h-36 resize-y bg-card leading-8" value={body} onChange={e => setBody(e.target.value)} placeholder="Start writing…" /></label><label className="block text-sm font-medium">Date<Input className="mt-2 bg-card" type="date" value={date} onChange={e => setDate(e.target.value)} required /></label>{editor === "diary" && <div><p className="mb-2 text-sm font-medium">How did it feel? <span className="font-normal text-muted-foreground">(optional)</span></p><div className="flex flex-wrap gap-2">{["happy","calm","okay","sad","anxious"].map(option => <Button key={option} type="button" variant={mood === option ? "default" : "outline"} className="capitalize" size="sm" onClick={() => setMood(mood === option ? null : option)}>{option}</Button>)}</div></div>}{message && <p role="alert" className="text-sm text-destructive">{message}</p>}<div className="flex justify-end gap-2 pt-2"><Button type="button" variant="ghost" onClick={() => setEditor(null)}>Cancel</Button><Button type="submit" disabled={saving}>{saving ? "Saving…" : editing ? "Save changes" : "Save to my space"}</Button></div></form></DialogContent></Dialog>
  </div>;
}
function ItemRow({ item, onEdit, onToggle, onDelete }: { item: Item; onEdit: () => void; onToggle: () => void; onDelete: () => void }) {
  const Icon = kinds.find(k => k.kind === item.kind)?.icon ?? BookOpen;
  return <div className="group flex items-start gap-3 py-4"><div className="mt-0.5 flex size-9 shrink-0 items-center justify-center rounded-md bg-wash text-primary"><Icon className="size-4" /></div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><button onClick={onEdit} className={`min-w-0 truncate text-left text-sm font-semibold hover:text-primary hover:underline ${item.completed ? "text-muted-foreground line-through" : ""}`}>{item.title}</button>{item.mood && <span className="rounded-sm bg-accent px-1.5 py-0.5 text-[10px] capitalize text-primary">{item.mood}</span>}</div><p className="mt-0.5 line-clamp-2 text-xs text-muted-foreground">{item.body || format(new Date(item.occurred_on + "T12:00:00"), "MMMM d, yyyy")}</p><span className="mt-1.5 block text-[10px] capitalize text-muted-foreground">{item.kind} · {format(new Date(item.occurred_on + "T12:00:00"), "MMM d")}</span></div>{item.kind === "task" && <Button variant="ghost" size="icon" onClick={onToggle} title={item.completed ? "Mark incomplete" : "Mark complete"} aria-label={item.completed ? "Mark incomplete" : "Mark complete"}>{item.completed ? <CheckCircle2 className="text-leaf-foreground" /> : <Circle />}</Button>}<Button variant="ghost" size="icon" onClick={onDelete} title="Delete" aria-label={`Delete ${item.title}`} className="text-muted-foreground hover:text-destructive"><Trash2 className="size-4" /></Button></div>;
}
