/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedDiaryRouteImport } from './routes/_authenticated/diary'
import { Route as AuthenticatedEventRouteImport } from './routes/_authenticated/event'
import { Route as AuthenticatedGoalRouteImport } from './routes/_authenticated/goal'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedMemoryRouteImport } from './routes/_authenticated/memory'
import { Route as AuthenticatedNoteRouteImport } from './routes/_authenticated/note'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTaskRouteImport } from './routes/_authenticated/task'
import { Route as AuthenticatedPeopleIndexRouteImport } from './routes/_authenticated/people.index'
import { Route as AuthenticatedPeoplePersonIdRouteImport } from './routes/_authenticated/people.$personId'
import { Route as ApiPublicPurgeAccountsRouteImport } from './routes/api/public/purge-accounts'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDiaryRoute = AuthenticatedDiaryRouteImport.update({
  id: '/diary',
  path: '/diary',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEventRoute = AuthenticatedEventRouteImport.update({
  id: '/event',
  path: '/event',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGoalRoute = AuthenticatedGoalRouteImport.update({
  id: '/goal',
  path: '/goal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMemoryRoute = AuthenticatedMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNoteRoute = AuthenticatedNoteRouteImport.update({
  id: '/note',
  path: '/note',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTaskRoute = AuthenticatedTaskRouteImport.update({
  id: '/task',
  path: '/task',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPeopleIndexRoute =
  AuthenticatedPeopleIndexRouteImport.update({
    id: '/people/',
    path: '/people/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPeoplePersonIdRoute =
  AuthenticatedPeoplePersonIdRouteImport.update({
    id: '/people/$personId',
    path: '/people/$personId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicPurgeAccountsRoute = ApiPublicPurgeAccountsRouteImport.update({
  id: '/api/public/purge-accounts',
  path: '/api/public/purge-accounts',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/diary': typeof AuthenticatedDiaryRoute
  '/event': typeof AuthenticatedEventRoute
  '/goal': typeof AuthenticatedGoalRoute
  '/home': typeof AuthenticatedHomeRoute
  '/memory': typeof AuthenticatedMemoryRoute
  '/note': typeof AuthenticatedNoteRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/task': typeof AuthenticatedTaskRoute
  '/people/$personId': typeof AuthenticatedPeoplePersonIdRoute
  '/api/public/purge-accounts': typeof ApiPublicPurgeAccountsRoute
  '/people/': typeof AuthenticatedPeopleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/diary': typeof AuthenticatedDiaryRoute
  '/event': typeof AuthenticatedEventRoute
  '/goal': typeof AuthenticatedGoalRoute
  '/home': typeof AuthenticatedHomeRoute
  '/memory': typeof AuthenticatedMemoryRoute
  '/note': typeof AuthenticatedNoteRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/task': typeof AuthenticatedTaskRoute
  '/people/$personId': typeof AuthenticatedPeoplePersonIdRoute
  '/api/public/purge-accounts': typeof ApiPublicPurgeAccountsRoute
  '/people': typeof AuthenticatedPeopleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/diary': typeof AuthenticatedDiaryRoute
  '/_authenticated/event': typeof AuthenticatedEventRoute
  '/_authenticated/goal': typeof AuthenticatedGoalRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/memory': typeof AuthenticatedMemoryRoute
  '/_authenticated/note': typeof AuthenticatedNoteRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/task': typeof AuthenticatedTaskRoute
  '/_authenticated/people/$personId': typeof AuthenticatedPeoplePersonIdRoute
  '/api/public/purge-accounts': typeof ApiPublicPurgeAccountsRoute
  '/_authenticated/people/': typeof AuthenticatedPeopleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/diary'
    | '/event'
    | '/goal'
    | '/home'
    | '/memory'
    | '/note'
    | '/profile'
    | '/search'
    | '/settings'
    | '/task'
    | '/people/$personId'
    | '/api/public/purge-accounts'
    | '/people/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/diary'
    | '/event'
    | '/goal'
    | '/home'
    | '/memory'
    | '/note'
    | '/profile'
    | '/search'
    | '/settings'
    | '/task'
    | '/people/$personId'
    | '/api/public/purge-accounts'
    | '/people'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/diary'
    | '/_authenticated/event'
    | '/_authenticated/goal'
    | '/_authenticated/home'
    | '/_authenticated/memory'
    | '/_authenticated/note'
    | '/_authenticated/profile'
    | '/_authenticated/search'
    | '/_authenticated/settings'
    | '/_authenticated/task'
    | '/_authenticated/people/$personId'
    | '/api/public/purge-accounts'
    | '/_authenticated/people/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicPurgeAccountsRoute: typeof ApiPublicPurgeAccountsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/diary': {
      id: '/_authenticated/diary'
      path: '/diary'
      fullPath: '/diary'
      preLoaderRoute: typeof AuthenticatedDiaryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/event': {
      id: '/_authenticated/event'
      path: '/event'
      fullPath: '/event'
      preLoaderRoute: typeof AuthenticatedEventRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/goal': {
      id: '/_authenticated/goal'
      path: '/goal'
      fullPath: '/goal'
      preLoaderRoute: typeof AuthenticatedGoalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/memory': {
      id: '/_authenticated/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof AuthenticatedMemoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/note': {
      id: '/_authenticated/note'
      path: '/note'
      fullPath: '/note'
      preLoaderRoute: typeof AuthenticatedNoteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/task': {
      id: '/_authenticated/task'
      path: '/task'
      fullPath: '/task'
      preLoaderRoute: typeof AuthenticatedTaskRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/people/': {
      id: '/_authenticated/people/'
      path: '/people'
      fullPath: '/people/'
      preLoaderRoute: typeof AuthenticatedPeopleIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/people/$personId': {
      id: '/_authenticated/people/$personId'
      path: '/people/$personId'
      fullPath: '/people/$personId'
      preLoaderRoute: typeof AuthenticatedPeoplePersonIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/purge-accounts': {
      id: '/api/public/purge-accounts'
      path: '/api/public/purge-accounts'
      fullPath: '/api/public/purge-accounts'
      preLoaderRoute: typeof ApiPublicPurgeAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDiaryRoute: typeof AuthenticatedDiaryRoute
  AuthenticatedEventRoute: typeof AuthenticatedEventRoute
  AuthenticatedGoalRoute: typeof AuthenticatedGoalRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedMemoryRoute: typeof AuthenticatedMemoryRoute
  AuthenticatedNoteRoute: typeof AuthenticatedNoteRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTaskRoute: typeof AuthenticatedTaskRoute
  AuthenticatedPeoplePersonIdRoute: typeof AuthenticatedPeoplePersonIdRoute
  AuthenticatedPeopleIndexRoute: typeof AuthenticatedPeopleIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDiaryRoute: AuthenticatedDiaryRoute,
  AuthenticatedEventRoute: AuthenticatedEventRoute,
  AuthenticatedGoalRoute: AuthenticatedGoalRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedMemoryRoute: AuthenticatedMemoryRoute,
  AuthenticatedNoteRoute: AuthenticatedNoteRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTaskRoute: AuthenticatedTaskRoute,
  AuthenticatedPeoplePersonIdRoute: AuthenticatedPeoplePersonIdRoute,
  AuthenticatedPeopleIndexRoute: AuthenticatedPeopleIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicPurgeAccountsRoute: ApiPublicPurgeAccountsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
