CREATE TABLE public.profiles (id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE, display_name text NOT NULL DEFAULT '', username text UNIQUE, avatar_url text, theme text NOT NULL DEFAULT 'system' CHECK (theme IN ('system','light','dark')), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT, INSERT, UPDATE, DELETE ON public.profiles TO authenticated;
GRANT ALL ON public.profiles TO service_role;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY profiles_owner_select ON public.profiles FOR SELECT TO authenticated USING (id = auth.uid());
CREATE POLICY profiles_owner_insert ON public.profiles FOR INSERT TO authenticated WITH CHECK (id = auth.uid());
CREATE POLICY profiles_owner_update ON public.profiles FOR UPDATE TO authenticated USING (id = auth.uid()) WITH CHECK (id = auth.uid());
CREATE POLICY profiles_owner_delete ON public.profiles FOR DELETE TO authenticated USING (id = auth.uid());
CREATE TABLE public.life_items (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), owner_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, kind text NOT NULL CHECK (kind IN ('diary','task','goal','note','memory','event')), title text NOT NULL DEFAULT '', body text NOT NULL DEFAULT '', occurred_on date NOT NULL DEFAULT current_date, due_on date, completed boolean NOT NULL DEFAULT false, mood text CHECK (mood IN ('happy','calm','okay','sad','anxious')), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT, INSERT, UPDATE, DELETE ON public.life_items TO authenticated;
GRANT ALL ON public.life_items TO service_role;
ALTER TABLE public.life_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY life_items_owner_select ON public.life_items FOR SELECT TO authenticated USING (owner_id = auth.uid());
CREATE POLICY life_items_owner_insert ON public.life_items FOR INSERT TO authenticated WITH CHECK (owner_id = auth.uid());
CREATE POLICY life_items_owner_update ON public.life_items FOR UPDATE TO authenticated USING (owner_id = auth.uid()) WITH CHECK (owner_id = auth.uid());
CREATE POLICY life_items_owner_delete ON public.life_items FOR DELETE TO authenticated USING (owner_id = auth.uid());
CREATE INDEX life_items_owner_date_idx ON public.life_items(owner_id, occurred_on DESC);
CREATE OR REPLACE FUNCTION public.touch_updated_at() RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$ BEGIN NEW.updated_at = now(); RETURN NEW; END $$;
CREATE TRIGGER profiles_touch_updated_at BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();
CREATE TRIGGER life_items_touch_updated_at BEFORE UPDATE ON public.life_items FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();